# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76dfd4c533022734e8f2e10c69e4b69d"
application_url = "https://importantly-tender-processor-metallic.trycloudflare.com"
embedded = true
name = "testApp"
handle = "testapp-2650"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "infotech222.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://importantly-tender-processor-metallic.trycloudflare.com/auth/callback",
  "https://importantly-tender-processor-metallic.trycloudflare.com/auth/shopify/callback",
  "https://importantly-tender-processor-metallic.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://importantly-tender-processor-metallic.trycloudflare.com/api/proxy"
subpath = "store-pickup"
prefix = "apps"

[pos]
embedded = false
